In [27]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv('Data_for_UCI_named.csv')
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [7]:
df.describe()

tau1          tau2          tau3          tau4            p1  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       5.250000      5.250001      5.250004      5.249997      3.750000   
std        2.742548      2.742549      2.742549      2.742556      0.752160   
min        0.500793      0.500141      0.500788      0.500473      1.582590   
25%        2.874892      2.875140      2.875522      2.874950      3.218300   
50%        5.250004      5.249981      5.249979      5.249734      3.751025   
75%        7.624690      7.624893      7.624948      7.624838      4.282420   
max        9.999469      9.999837      9.999450      9.999443      5.864418   

                 p2            p3            p4            g1            g2  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean      -1.250000     -1.250000     -1.250000      0.525000      0.525000   
std        0.433035      0.433035      0.433035      0.274256      0.274255   
min       -1.999891     -1.999945     -1.999926      0.050009      0.050053   
25%       -1.624901     -1.625025     -1.624960      0.287521      0.287552   
50%       -1.249966     -1.249974     -1.250007      0.525009      0.525003   
75%       -0.874977     -0.875043     -0.875065      0.762435      0.762490   
max       -0.500108     -0.500072     -0.500025      0.999937      0.999944   

                 g3            g4          stab  
count  10000.000000  10000.000000  10000.000000  
mean       0.525000      0.525000      0.015731  
std        0.274255      0.274255      0.036919  
min        0.050054      0.050028     -0.080760  
25%        0.287514      0.287494     -0.015557  
50%        0.525015      0.525002      0.017142  
75%        0.762440      0.762433      0.044878  
max        0.999982      0.999930      0.109403

In [8]:
df.isnull().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [9]:

df = df.drop('stab',axis=1)


In [10]:
df.columns

Index(['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2',
       'g3', 'g4', 'stabf'],
      dtype='object')

In [11]:
df.isnull().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stabf    0
dtype: int64

In [12]:
X_data=df.drop('stabf', axis=1)
Y_data=df[['stabf']]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(X_data, Y_data, test_size=0.3, random_state=1)
y_train.value_counts()

stabf   
unstable    4464
stable      2536
dtype: int64

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
train_Scaler=pd.DataFrame(scaler.fit_transform(x_train), columns=x_train.columns)
test_Scaler=pd.DataFrame(scaler.transform(x_test), columns=x_test.columns)
print(train_Scaler.head())
print(test_Scaler.head())

       tau1      tau2      tau3      tau4        p1        p2        p3  \
0  1.639174 -1.177014 -0.467121 -0.813608 -1.662068  0.615944  0.662838   
1  1.455566  0.151849  0.061654  0.973640 -0.349336 -0.101824  1.500031   
2  1.651664 -0.655617 -0.925842 -0.997175 -0.665464 -0.791600  0.384268   
3  0.386923 -0.270755 -0.943688 -0.743232 -0.368194  0.953704 -0.945065   
4 -1.529162 -0.694073 -1.130362 -1.004901 -0.006393 -1.517632  1.667195   

         p4        g1        g2        g3        g4  
0  1.615579  1.531472  0.944686  0.565311 -0.869033  
1 -0.783289  0.738984 -1.624029 -0.015254 -0.966545  
2  1.563036  1.570947 -1.414968 -1.232809 -0.085111  
3  0.629575  0.769530  1.264642 -0.422865  0.994099  
4 -0.134907  0.354095  0.696427 -1.535591  0.407953  
       tau1      tau2      tau3      tau4        p1        p2        p3  \
0  0.598597 -0.408514  1.502751  1.109213  0.402772 -1.495828 -0.786984   
1  0.207836  0.377840 -0.190311 -0.529572 -0.228513 -1.062053  0.422150   


In [16]:
from sklearn.ensemble import RandomForestClassifier
Rf=RandomForestClassifier(n_estimators=100, random_state=1)
Rf.fit(train_Scaler,y_train)
prediction=pd.Series(Rf.predict(test_Scaler))
prediction.value_counts()

C:\Users\USER\AppData\Local\Temp/ipykernel_7532/323825368.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  Rf.fit(train_Scaler,y_train)


unstable    1972
stable      1028
dtype: int64

In [28]:
#label encoding for the categorical data of column 'stabf'
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_train =pd.DataFrame(encoder.fit_transform(y_train.reset_index(drop=True)), columns=y_train.columns)
y_test = pd.DataFrame(encoder.transform(y_test.reset_index(drop=True)),columns=y_test.columns) 
def score_data(y_test,pred_y, clf):
  print('\n\n'+clf)
  print("\n CONFUSION MATRIX \n", confusion_matrix(y_test,pred_y))
  print(classification_report(y_test,pred_y))
  print("Accuracy Score is: ", accuracy_score(y_test, pred_y))
#Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier
Rf=RandomForestClassifier(n_estimators=100, random_state=1)
Rf.fit(train_Scaler,y_train)
pred=pd.Series(Rf.predict(test_Scaler))
pred.value_counts()

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
score_data(y_test, prediction,'RandomForest-Classifier')
RandomForest-Classifier

            



RandomForest-Classifier


TypeError: Labels in y_true and y_pred should be of the same type. Got y_true=[0 1] and y_pred=['stable' 'unstable']. Make sure that the predictions provided by the classifier coincides with the true labels.

In [29]:
from xgboost import XGBClassifier
classifier=XGBClassifier()
classifier.fit(train_Scaler,y_train)
prediction=classifier.predict(test_Scaler)
score_data(y_test, prediction,'XGBClassifier')
XGBClassifier

[22:19:07] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier

 CONFUSION MATRIX 
 [[ 981  103]
 [  73 1843]]
              precision    recall  f1-score   support

           0       0.93      0.90      0.92      1084
           1       0.95      0.96      0.95      1916

    accuracy                           0.94      3000
   macro avg       0.94      0.93      0.94      3000
weighted avg       0.94      0.94      0.94      3000

Accuracy Score is:  0.9413333333333334


xgboost.sklearn.XGBClassifier

In [31]:
#LGBM Classifier

from lightgbm import LGBMClassifier
classify= LGBMClassifier()
classify.fit(train_Scaler,y_train)
prediction=classify.predict(test_Scaler)
score_data(y_test, prediction,'LGBM')
LGBM



LGBM

 CONFUSION MATRIX 
 [[ 985   99]
 [  83 1833]]
              precision    recall  f1-score   support

           0       0.92      0.91      0.92      1084
           1       0.95      0.96      0.95      1916

    accuracy                           0.94      3000
   macro avg       0.94      0.93      0.93      3000
weighted avg       0.94      0.94      0.94      3000

Accuracy Score is:  0.9393333333333334


NameError: name 'LGBM' is not defined

In [20]:
from sklearn.ensemble import ExtraTreesClassifier
etc=ExtraTreesClassifier()
etc.fit(train_Scaler,y_train)
predict=etc.predict(test_Scaler)
score_data(y_test, predict, 'ExtraTreesClassifier-Initially')
ExtraTreesClassifier-Initially




ExtraTreesClassifier-Initially

 CONFUSION MATRIX 
 [[ 687   25]
 [   5 1283]]
              precision    recall  f1-score   support

           0       0.99      0.96      0.98       712
           1       0.98      1.00      0.99      1288

    accuracy                           0.98      2000
   macro avg       0.99      0.98      0.98      2000
weighted avg       0.99      0.98      0.98      2000

Accuracy Score is:  0.985


NameError: name 'Initially' is not defined

In [39]:
#Feature Importances for Optimal Model of ExtraTreesClassifier
from sklearn.ensemble import ExtraTreesClassifier
etc=ExtraTreesClassifier()
etc.fit(Xt_Scaled,y_train()
features=etc_opt.feature_importances_

fill=pd.DataFrame(feature_imp, index=train_Scaler.columns, columns=['Importance'])
print("Max Importance is of: ", fill[['Importance']].idxmax())
print("Min Importance is of: ", fill[['Importance']].idxmin()

SyntaxError: invalid syntax. Perhaps you forgot a comma? (Temp/ipykernel_7532/648728243.py, line 4)